name: External Trigger Workflow

on:
  repository_dispatch:
    types:
      - custom-event

jobs:
  external:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by an external event!"
      - run: echo "Client payload value: ${{ github.event.client_payload.my_key }}"
